### ISSUE TITLE
Porting the rest of arcade.math

### ISSUE THREAD

**Issue by Cleptomania** [pythonarcade/arcade-accelerate#4]
We have ported the `clamp` and `rotate_point` function from the `arcade.math` module. There are many more simple math functions within that module that would be a good starting place for anyone looking to get involved in working on this project. It is very likely that some of these functions will see no direct speedup being moved to Rust, however a lot of benefits come from having more things in Rust, so as we port things that utilize these functions, the need to go back and forth to python to access these will help those areas achieve more substantial speedups.

We may not end up patching in all of these functions, but having them available to start to use when they're needed will be useful.

This issue is being created to track work on functions which need ported, I've added a checklist below of the functions. It is very likely 

- [x] clamp
- [x] lerp
- [x] lerp_vec
- [x] lerp_angle
- [x] rand_in_rect
- [x] rand_in_circle
- [x] rand_on_circle
- [x] rand_on_line
- [x] rand_angle_360_deg
- [x] rand_angle_spread_deg
- [x] rand_vec_spread_deg
- [x] rand_vec_magnitude
- [x] get_distance
- [x] rotate_point
- [x] get_angle_degrees
- [x] get_angle_radians

**Comment by Cleptomania** [comment]
As of PR #9 being merged we are only missing two functions from `arcade.math`.

A follow up to this issue may be to go through and add some timing benchmarks for these functions to get an idea of how much benefit the Rust versions give.

**Comment by yuki242** [comment]
the remaining functions are using a method `from_polar` from `_Vec2` class. Should i port the `_Vec2` class or can i just make an extra function `from_polar` and use it.

**Comment by yuki242** [comment]
`lerp(2.0, 3.0, 1.0)`: python=0.273765 rust=0.216185 -> 1.266 x faster

`lerp_vec((1.0, 2.0), (3.0, 4.0), 1.0)`: python=0.713570 rust=0.336879 -> 2.118 x faster

`lerp_angle(45.0, 90.0, 1.0)`: python=0.750661 rust=0.230527 -> 3.256 x faster

`rand_in_rect((0.0, 0.0), 9.0, 9.0)`: python=1.077636 rust=0.366872 -> 2.937 x faster

`rand_in_circle((0.0, 0.0), 9.0)`: python=1.005056 rust=0.348362 -> 2.885 x faster

`rand_on_circle((0.0, 0.0), 1.0): python=0.879215 rust=0.348887 -> 2.520 x faster`

`rand_on_line((0.0, 0.0), (9.0, 9.0))`: python=1.222107 rust=0.344790 -> 3.544 x faster

`rand_angle_360_deg()`: python=0.520563 rust=0.189494 -> 2.747 x faster

`rand_angle_spread_deg(45.0, 90.0)`: python=0.582991 rust=0.210458 -> 2.770 x faster

`get_distance(2.0, 3.0, 4.0, 5.0)`: python=0.366116 rust=0.215763 -> 1.697 x faster

`get_angle_degrees(1.0, 2.0, 3.0, 4.0)`: python=0.470308 rust=0.242213 -> 1.942 x faster

`get_angle_radians(1.0, 2.0, 3.0, 4.0)`: python=0.372859 rust=0.240203 -> 1.552 x faster

this was the output from `tests/perf_compare.py` script

**Comment by jf22201** [comment]
#

> the remaining functions are using a method `from_polar` from `_Vec2` class. Should i port the `_Vec2` class or can i just make an extra function `from_polar` and use it.

I have made an attempt to port the last two functions by porting the _Vec2 class but only the from_polar and as_tuple methods.

**Comment by Cleptomania** [comment]
I think porting the whole class is fine for now. I need to do some auditing of Arcade's usage of the class, I think we are maybe moving away from that in favor of using `pyglet.math.Vec2` but I'm not sure where things are at with that, so for now I think porting the whole class is fine.

**Comment by Cleptomania** [comment]
I'm going to go ahead and close this as we have everything covered functionality/test wise. The only thing I'd like to see related to this is benchmarks added, however benchmarking in arcade-accelerate as a whole needs a more holistic solution so I don't think it makes sense to try and track that work here.
